### ISSUE TITLE
Support running when multiple FIDO2 devices are detected

### ISSUE THREAD

**Issue by mntn-xyz** [olastor/age-plugin-fido2-hmac#21] opened 2024-12-12 01:05 UTC
Currently when multiple devices are detected, the program simply shows an error and exits: https://github.com/olastor/age-plugin-fido2-hmac/blob/ef81e6745ef085df57e8fc659bd8bf6010c3b4eb/pkg/plugin/fido2_utils.go#L17

I have pcscd enabled which causes my one key to show up as two devices. I'm able to use this by disabling pcscd, but it would be nice if this had better behavior when multiple devices are detected.

Since it's not possible to distinguish between same-vendor-and-model FIDO2 devices based on the aaguid, and since /dev paths can change between inserts, I'm not sure what the ideal solution is. For me it would be adequate to just try the first available device, but others may have different use cases. I suppose that an environment variable might work; the user could set up udev rules with a vendor-specific tool to identify the device and set this variable accordingly.

*Edit:* after some thought, it would be best to have an optional variable pointing to a file which may contain the device path. If the variable is set, the file exists, and the file is not empty and contains a device, the listed device is preferred. Otherwise the first device found is used, but a warning is printed that multiple devices are present. This would "just work" for most people, would be easy to troubleshoot, and supports edge cases.

**Comment by olastor** [comment] 2024-12-12 16:29
@mntn-xyz Thanks for your request. There's definitely room for improvment, the error message you mentioned I added because  I wanted to avoid implementing a complicated solution for multiple devices when I was focusing on the core functionality. I created #2 which is related. I think now that this comes up again I can look into it.

> I have pcscd enabled which causes my one key to show up as two devices. I'm able to use this by disabling pcscd, but it would be nice if this had better behavior when multiple devices are detected.

This seems to be yet another edge case. I am not able to reproduce that easily on my side, but I am wondering if this specific issue could be resolved just by adding a better filtering when detecting possible devices. Do both devices show up with the same properties when checking `sudo fido2-token -I /dev/hidraw0`? Do both have the same version and extension strings? 

e.g.

```
version strings: U2F_V2, FIDO_2_0, FIDO_2_1_PRE
extension strings: credProtect, hmac-secret
```
> Since it's not possible to distinguish between same-vendor-and-model FIDO2 devices based on the aaguid, and since /dev paths can change between inserts, I'm not sure what the ideal solution is. For me it would be adequate to just try the first available device, but others may have different use cases. I suppose that an environment variable might work; the user could set up udev rules with a vendor-specific tool to identify the device and set this variable accordingly.

Exactly, that's the caveat. There is no real token identifier and the `/dev/hid*` paths are ephemeral. Some keys might have a unique ID like the Yubikey 4/5 (not the fido2-only version), but are most likely an exception. I think adding support for an env variable could be useful. I'd probably add show warning when it's a path starting with "/dev/hid". In this case the plugin user is responsible for making sure that variable is correct.

> Edit: after some thought, it would be best to have an optional variable pointing to a file which may contain the device path. If the variable is set, the file exists, and the file is not empty and contains a device, the listed device is preferred. Otherwise the first device found is used, but a warning is printed that multiple devices are present. This would "just work" for most people, would be easy to troubleshoot, and supports edge cases.

I think I'd prefer getting the path from the env variable, but also resolve any symlinks. That way any path of udev rules are supported (which will be symlinks) and also custom symlinks can be used, which I think has the same advantages of your suggestion because the same symlink can just be changed to point to a different path. Or are there more benefits when reading the path from a file that I missed? For most users, creating both a file with the correct path and setting an env variable could be too cumbersome to actually use it.

I think for the case when there are multiple tokens, but no preference is set, I'll try to see if a manual selection of the token could work by sending the assertion to all devices simultaneously and then only continuing for the device that is first touched. There is an [example in the python3 libfido2](https://github.com/Yubico/python-fido2/blob/8b5939a4c5cc60285416bf7a5b4ba7e2e26f3d51/fido2/client.py#L560) package. There seems to even be a special command for selection, but I didn't find support for that yet in the golang library.

**Comment by mntn-xyz** [comment] 2024-12-12 20:14
> Do both have the same version and extension strings?

As far as I can tell only one hidraw device is created. Running `fido2-token -L` shows both an hidraw device and a device at pcsc://slot0. Running `fido2-token -I pcsc://slot0` shows minimal output:

```
fido2-token -I pcsc://slot0
proto: 0x00
major: 0x00
minor: 0x00
build: 0x00
caps: 0x00 (nowink, nocbor, msg)
```

So as a fix for just my issue, maybe you could ignore devices lacking version strings, aaguid, or other critical fields. For allowing multiple keys to be inserted, I like your idea of an env var + symlinks. That should just be as flexible without being as hackish as my suggestion. As long as the user sets a static symlink path, they can update that symlink as needed dynamically without requiring the user to refresh env vars (that is what I was attempting to solve).

Multiple tokens/no preference also sounds like a reasonable approach. You may still want to print a warning so users with multiple keys won't create unnecessary bug reports!

**Comment by olastor** [comment] 2024-12-12 21:06
@mntn-xyz Do you have go installed and can compile locally? I have created https://github.com/olastor/age-plugin-fido2-hmac/pull/24 to ignore devices that are not fido2 or do not have the hmac-secret extension, but I cannot test if it fixes your case.

**Comment by mntn-xyz** [comment] 2024-12-13 16:00
Don't have a Go env set up but I can use a nix override to test

**Comment by mntn-xyz** [comment] 2024-12-13 17:27
Fix works perfectly. If anyone else is on NixOS with a vanilla flake config, just add this to the nixosSystem modules in flake.nix:

```
{
  nixpkgs.overlays = [ (final: prev: {
    age-plugin-fido2-hmac = prev.age-plugin-fido2-hmac.overrideAttrs (_oldAttrs: {
      src = prev.fetchFromGitHub {
        owner = "olastor";
        repo = "age-plugin-fido2-hmac";
        rev = "0e699d85c0a27db662edd8f9ddf705386b0878e5";
        hash = "sha256-eRgoe9iFpeRdb7w35ed2w5CMqhigcKsJhuqQSk8Y5hw=";
      };
    });
  })];
}
```

This will use the PR branch until it's upstreamed. Feel free to close the issue if you want, or leave it open if you want it as a reference/reminder for the multiple devices scenario.

**Comment by olastor** [comment] 2024-12-13 17:47
@mntn-xyz Awesome, thanks for testing! I'll push a new patch release for this.

I think I'll close this issue, but still add the other ideas about handling multiple tokens to #2 .

**Closed** 2024-12-13 17:47 UTC
